wmnsk/go-pfcp

ie/application-id.go
ie/application-instance-id.go
ie/bar-id.go
ie/flow-information.go
ie/ie_test.go
ie/metric.go
ie/oci-flags.go
ie/packet-detection-rule-id.go
ie/pfd-contents.go
ie/sequence-number.go
ie/timer.go
ie/urr-id.go

To retrieve needed values from a grouped IE quickly, some helper methods for some IEs return the value if the type of IE matches to the IE that may include that type.
For example, `URRID()` now returns the value in uint32 if it's called on QueryURR IE as well as on URRID IE.

Add helper functions for grouped IEs

---

ie/outer-header-creation.go

This change fixes incorrect offset computation to the start of the Outer Header Creation IE parsing.

Fix OuterHeaderCreation parse initial offset

---

go.mod
go.sum
ie/ie.go
internal/logger/logger.go
logger.go
message/message.go
message/session-establishment-request_test.go

Sometimes we want to warn something trivial to users instead of returning errors. This PR implements a logger used in common in the whole project(go-pfcp) that can be disabled or replaced with another `log.Logger`.

Add project-wide logger for informational logs

---

ie/flow-information.go
ie/forwarding-policy.go
ie/ie_string_test.go
ie/node-id.go
ie/smf-set-id.go
ie/ue-ip-address-pool-identity.go

* Fixed some methods that return string values (incl. fix #59)
* Added tests for such methods

Fix IE helper methods that return values in string

---

ie/far-id.go

This patch fixes retrieving of the right FARID from IE for a received RemoveFAR pfpc request.

Extract the right FARID filed in RemoveFAR request

---

ie/ue-ip-address.go

In case of UPF UE IP allocation feature support, UE IP address received from SMF would only contain the flag value CHV4 true. In that case length of UE IP address would 1 for the flags.
29.244 : 8.2.62 UE IP Address
Bit 5 – CHV4 (CHOOSE IPV4): If this bit is set to "1", then the V4 bit shall not be set, the IPv4 address shall
not be present and the UP function shall assign an IPv4 address. This bit shall only be set by the CP function.

UE IP Address length limit fix

---

message/message.go

In function Parse(), validating the len of b should be 2 instead of 1 due to array index start from 0, and also PFCP Message Type reside in array index 1 of a given byte stream.

In function Parse(), validating the len of b should be 2 instead of

---

ie/outer-header-removal.go

The size of the OuterHeaderRemoval IE was one octet in 3GPP TS
29.244 up to V15.3.0, but it has been changed to two octets since
V15.4.0.
The following commit fixes it so that it does not cause an error
even in OuterHeaderRemoval IE with size 1 according to V15.3.0 or
earlier, but when GTPUExternsionHeaderDeletion is called in
OuterHeaderRemoval IE with size 1, v[1] access and index out of
range error will occur.
https://github.com/wmnsk/go-pfcp/commit/78b3fd79723d4ef6e844acb5e31780867c3247f3
This patch fixes OuterHeaderRemoval IE with size 1 to return 0 when
GTPUExternsionHeaderDeletion is called. But, perhaps it would have
been better to make it return an error.

The size of the OuterHeaderRemoval IE and GTPUExternsionHeaderDeletion handling

---

ie/gate-status.go
ie/ie_uint8_test.go

And also add new tests to cover all possible encoding/decoding combinations.
Test failures without the fix:
```
➜  go-pfcp git:(fix-gate-status-decode) ✗ go test ie/ie_uint8_test.go 
--- FAIL: TestUint8IEs (0.01s)
--- FAIL: TestUint8IEs/GateStatus/ClosedOpen/GateStatusDL (0.00s)
ie_uint8_test.go:1245:   uint8(
-   4,
+   0,
)
--- FAIL: TestUint8IEs/GateStatus/ClosedClosed/GateStatusDL (0.00s)
ie_uint8_test.go:1245:   uint8(
-   5,
+   1,
)
```

Fix decoding of GateStatusDL

---

ie/gate-status.go

The fix introduced in #91 extracts only one bit from the UL/DL gate fields. However, according to spec, all bits (2) should be extracted to allow for future uses.
cc @krsna1729

Make gate status extraction future-proof

---

ie/ue-ip-address.go

- `HasCH` is removed and replaced by `HasCHV4`
- `HasCHV6` and `HasIP6PL` are new methods

Add missing methods in UE IP Address IE

---

ie/outer-header-creation.go

- Now it is possible to check fields presence directly using `OuterHeaderCreationFields`
- New method `HasPortNumber` to check the presence of the `Port Number` field
- New method `HasLLSSMCTEID` to check the new `Low Layer SSM and C-TEID` bit introduced in release 17.2.0
- Fix various typos in godoc

Add missing methods for Outer Header Creation Description

---

examples/heartbeat/hb-client/main.go
examples/heartbeat/hb-server/main.go

Signed-off-by: Oriol Batalla <obatalla@fb.com>
When trying to run HB example client and server, we get an error 
```
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00008a180, {0x1135010, 0xc000012630}, {0x110cb87, 0x100dca7}, {0x11101b0, 0x1109da0})
/usr/local/Cellar/go@1.17/1.17.8/libexec/src/flag/flag.go:864 +0x439
flag.(*FlagSet).StringVar(...)
/usr/local/Cellar/go@1.17/1.17.8/libexec/src/flag/flag.go:762
flag.(*FlagSet).String(0xc00005d370, {0x110cb87, 0x2}, {0x110e5a1, 0xe}, {0x11101b0, 0x16})
/usr/local/Cellar/go@1.17/1.17.8/libexec/src/flag/flag.go:775 +0xac
flag.String(...)
/usr/local/Cellar/go@1.17/1.17.8/libexec/src/flag/flag.go:782
main.main()
/Users/obatalla/testgit/go-pfcp/examples/heartbeat/hb-server/main.go:23 +0x57
Process finished with the exit code 2
```
This error leads …

fix: remove - from flag argument on HB example client adn server

---

message/message.go

It will be useful to assign and set sequence number for the built message before it is sent out.

Add SetSequenceNumber() to Message interface

---

ie/ie_test.go
ie/ie_uint16_test.go
ie/ie_uint32_test.go
ie/reporting-triggers.go
ie/usage-report-trigger.go
message/session-establishment-request_test.go
message/session-modification-request_test.go

Note: it is an API breaking change:
- NewReportingTriggers must provide multiple uint8 parameter instead of uint16.
- ReportingTriggers return a byte slice instead of uint16.
Align with NewUsageReportTrigger and UsageReportTrigger.

Add more new flags in ReportingTriggers/UsageReportTrigger IE

---

ie/apply-action.go

The previous PR(https://github.com/wmnsk/go-pfcp/pull/109) breaks helper function original usage, ex: can not use farIe.HasFORW(), only can use applyActionIe.HasFORW().
This PR fixes ApplyAction IE's helper functions (HasFORW/HasNOCP/HasDUPL/HasIPMA/HasIPMD/HasDFRT/HasEDRT/HasBDPN/HasDDPN/HasFSSM/HasMBSU) to be backward-compatible with original usage.

fix ApplyAction IE's helper functions

---

ie/reporting-triggers.go
ie/usage-report-trigger.go

Leverage ReportingTriggers() in helper functions to recursively get the value.
Let helper functions be able to use with any IE, not only with ReportingTriggers IE.

Enhance ReportingTriggers related helper functions usage

---

ie/apply-action.go

Leverage ApplyAction()/DataStatus() in helper functions to recursively get the value.
Let helper functions be able to use with any IE, not only with ApplyAction/DataStatus IE.

Enhance HasDROP()/HasBUFF() helper functions usage

---

README.md
ie/ie.go
message/message.go

This PR introduces the parsing functions which copies the given buffer before accessing it to avoid race conditions when the given buffer is used in goroutines. Without this, users need to copy the buffer by themselves like this: 
https://github.com/wmnsk/go-gtp/blob/7977494dd5165da2e89adf986f8c6cf374d9f486/gtpv2/conn.go#L192
_Example is from go-gtp project, as go-pfcp doesn't have networking functionalities yet._
The added functions for IEs are of the same concept. Not needed in most use-cases I guess, though.

Add safe parsing functions

---

README.md
ie/ie.go
message/message.go

because it's not actually safe enough
Resolves #129

Remove ParseSafe

---

ie/cp-function-features.go
ie/ie_byte_array_test.go
ie/ie_uint8_test.go

Add the missing Additional Supported-Features field in CPFunctionFeatures, which has been described in rel.16 but not handled correctly. Borrowing the work in https://github.com/wmnsk/go-pfcp/pull/114 by @louisroyer.

Handle Additional Supported-Features 
